remote_theme: zynomon/wiker
title: "Vex"
thumbnail: "/thumb.png"
url: "https://zynomon.github.io/vex"
icon: "/vex.svg"
accent: green

header:
  logo: "/headerlogo.svg"
  bg-wrapper: auto
  bg: "https://gitlab.com/zynomon/svg-papers/-/raw/main/leaves/leaves.png"
  a:
    - order: 1
      url: "/downloads"
      text: "Downloads"
      icon: "https://api.iconify.design/fluent-color:arrow-square-down-32.svg"
    - order: 2
      url: "/wiki"
      text: "Wiki"
      icon: "https://api.iconify.design/fluent-color:document-text-32.svg"
    - order: 3
      url: "https://github.com/zynomon/vex"
      text: "GitHub"
    - order: 4
      url: "https://gitlab.com/zynomon/vex"
      text: "GitLab"

footer:
  logo:
    link: "/headerlogo.svg"
    height: "32px"
    width: "auto"
  notice-text: "Vex team"
  a:
    - order: 1
      url: "https://github.com/zynomon"
      text: "GitHub"
    - order: 2
      url: "https://codeberg.org/zynomon"
      text: "Codeberg"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-remote-theme