remote_theme: zynomon/wiker
title: "Vex"
description: "Vex an extensive text editor"
image: "https://repository-images.githubusercontent.com/1070654301/4644cccf-adea-4ea2-9155-9ae324e8cce5"
url: "https://zynomon.github.io/vex"

header:
  logo: "https://github.com/user-attachments/assets/3687d8ab-fc65-45a4-836d-4de590366d14"
  bg: "https://gitlab.com/zynomon/svg-papers/-/raw/main/leaves/leaves.png"
  a:
    - order: 1
      url: "https://github.com/zynomon/vex"
      text: "GitHub"
      icon: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
    - order: 2
      url: "https://gitlab.com/zynomon/vex"
      text: "GitLab"
      icon: "https://cdn-icons-png.flaticon.com/512/5968/5968853.png"


footer:
  logo:
    link: "https://github.com/user-attachments/assets/3687d8ab-fc65-45a4-836d-4de590366d14"
    height: "32px"
    width: "auto"
  notice-text: "Vex team.."
  a:
    - order: 1
      url: "https://github.com/zynomon"
      text: "GitHub"
      icon: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
    - order: 2
      url: "https://codeberg.org/zynomon"
      text: "Codeberg"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

  
